title: App
data:
  name: 'Cheng Hsin Sverige'
  description: 'Skill, sensitivity, awareness | Färdighet, känslighet, medvetenhet'
  keywords: 'cheng hsin,göteborg,dojo,aikido,zen,taiji,tai chi,skill,awareness'
  author: 'Vlad Dumitrescu'
  webmasterContact: 'webmaster@chenghsin.se'
  googleTag: 'UA-2373857-13'